// Laxico Advertising Initial Default Database (LocalStorage Fallback & Seed Data)

export const initialSettings = {
  id: 'default',
  site_name: 'Laxico Advertising',
  tagline: 'Billboard & Poster Placements Across India',
  featured_brands: 'NIKE, ZOMATO, SAMSUNG, HDFC BANK, COCA-COLA, AMAZON, TATA, SWIGGY, BOAT, MYNTRA',
  brand_subtitle: 'OUTDOOR • TRANSIT • DIGITAL',
  logo_text: 'LAXICO',
  logo_subtext: 'ADS',
  logo_badge: 'L',
  logo_url: '/logo.png', // Admin upload can replace this local default
  favicon_url: '/logo.png', // Admin upload can replace this local default
  meta_title: 'Laxico Advertising — Billboard & Poster Placements Across India',
  meta_description: 'Laxico Advertising manages 250+ premium billboard & poster placements across metros, airports, highways and malls in India.',
  phone: '9742313705',
  phone_alt: '9742313705',
  whatsapp: '9742313705',
  email: 'lexicoadvertising@gmail.com',
  email_sales: 'lexicoadvertising@gmail.com',
  udyam_number: 'UDYAM-KR-03-0664055',
  gst_number: '29CTIPS2521P1ZZ',
  about_label: 'Since 2025',
  about_title: 'About Laxico & Contact',
  about_description: "From 3 billboards on NH-8 to India's most data-driven outdoor network — we blend prime media ownership with performance tracking every CMO loves.",
  about_years: '16+',
  about_team_count: '40+',
  about_ad_spend: '₹120Cr',
  about_mission: 'Make outdoor advertising as measurable and effortless as digital — with verified footfall, transparent pricing and photo-proof of every display.',
  about_vision: 'A Laxico screen within 10 minutes of every urban Indian — powering local businesses and national brands alike across 50 cities by 2030.',
  about_retention_title: 'Why clients stay',
  about_retention_description: '98% retention. Single-point ownership, in-house printing, night monitoring patrols and a client dashboard with live display photos.',
  about_image_1: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?q=80&w=700&auto=format&fit=crop',
  about_image_2: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=700&auto=format&fit=crop',
  about_timeline: '[]',
  about_team: '[]',
  contact_label: 'Get a quote',
  contact_title: 'Contact / Inquiry',
  contact_description: 'Select your service & location. Our strategist replies with photos, footfall & pricing within 4 working hours.',
  contact_response_title: '4-hr response',
  contact_approved_title: '100% Approved',
  contact_faqs: JSON.stringify([
    { q: 'How fast can my ad go live?', a: '48 hours from artwork approval — including printing, mounting and illumination. Airport & metro sites may need 72 hrs for security clearance.' },
    { q: 'Are your sites government-approved?', a: 'Yes. Every Laxico site carries MCD / DMRC / AAI / railway approvals. We share permit copies with your invoice.' },
    { q: 'Do you handle printing?', a: 'In-house plant in Delhi. 720 DPI flex, vinyl & backlit from ₹8,500 per site with free installation.' },
    { q: 'How do I get proof my ad is displayed?', a: 'Geo-tagged day + night photos every week on WhatsApp, plus a completion report with traffic data.' },
    { q: 'What is the minimum booking?', a: 'Street kiosks: 20 poles / 1 month. Billboards & transit: 1 site / 1 month. LEDs: 1 week.' }
  ]),
  support_hours: 'Mon–Sat • 10:00 AM – 7:00 PM IST',
  head_office: 'No 1 Nandini Complex, Chandra Layout, Bangalore — 560040',
  office_mumbai: 'BKC Office, Bandra Kurla Complex, Mumbai — 400051',
  office_bengaluru: 'HSR Office, Sector 1, HSR Layout, Bengaluru — 560102',
  map_link: 'https://maps.google.com/?q=No+1+Nandini+Complex+Chandra+Layout+Bangalore+560040',
  cities: 'Delhi • Mumbai • Bengaluru • Hyderabad',
  active_sites_count: '248',
  campaigns_count: 1250,
  locations_count: 248,
  retention_rate: 98,
  social_links: {
    facebook: 'https://facebook.com',
    instagram: 'https://instagram.com',
    twitter: 'https://twitter.com',
    youtube: 'https://youtube.com'
  },
  genre_badges: JSON.stringify({
    Airport: { active: true, text: 'HOT', color: 'red' },
    Cinema: { active: true, text: 'HOT', color: 'red' },
    Digital: { active: true, text: 'HOT', color: 'red' },
    Outdoor: { active: true, text: 'HOT', color: 'red' },
    Transit: { active: true, text: 'HOT', color: 'red' },
    Retail: { active: false, text: 'POPULAR', color: 'purple' },
    'Street Furniture': { active: false, text: 'TRENDING', color: 'amber' },
    BTL: { active: false, text: 'NEW', color: 'emerald' },
    Print: { active: false, text: 'CLASSIC', color: 'blue' },
    Radio: { active: false, text: 'TRENDING', color: 'amber' },
    Sports: { active: false, text: 'HOT', color: 'red' },
    Television: { active: false, text: 'PRIME', color: 'purple' },
    Socialmedia: { active: true, text: 'TRENDING', color: 'red' },
    Development: { active: true, text: 'NEW', color: 'emerald' },
    'Drone Marketing': { active: true, text: 'HOT', color: 'purple' }
  })
};

export const initialServices = [
  // --- AIRLINE / AIRPORT (Per-City Airport Listings) ---
  {
    id: 'svc_airport_delhi',
    name: 'Delhi Airport Advertising',
    type: 'Airport',
    genre: 'Airport',
    sub_type: 'Terminal T3 & T2 Departures & Arrivals',
    chain_or_brand: 'Indira Gandhi International Airport',
    audience_metric: '5.8M+ Monthly Passengers • High CXO Density',
    min_spend: 75000,
    price: 180000,
    rating: 4.9,
    popularity: 98,
    status: 'Active',
    dims: '30 × 12 ft Static Lightboxes & Digital Video Walls',
    durations: '1 Month, 3 Months, 6 Months, 12 Months',
    cities: 'Delhi NCR',
    image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?q=80&w=800&auto=format&fit=crop',
    description: 'High-impact static lightboxes, digital video walls, and baggage-belt conveyor wraps across Terminal 3 and Terminal 2. Captive exposure targeting affluent domestic and international business flyers with average dwell time exceeding 45 minutes.'
  },
  {
    id: 'svc_airport_mumbai',
    name: 'Mumbai Airport Advertising',
    type: 'Airport',
    genre: 'Airport',
    sub_type: 'Terminal T2 Aerobridge & Concourse Wraps',
    chain_or_brand: 'Chhatrapati Shivaji Maharaj International Airport',
    audience_metric: '4.5M+ Monthly Flyers • Premier HNI Gateway',
    min_spend: 70000,
    price: 175000,
    rating: 4.9,
    popularity: 97,
    status: 'Active',
    dims: '25 × 10 ft Backlit Panels & Aerobridge Glass Wraps',
    durations: '1 Month, 3 Months, 6 Months, 12 Months',
    cities: 'Mumbai',
    image: 'https://images.unsplash.com/photo-1542296332-2e4473faf563?q=80&w=800&auto=format&fit=crop',
    description: 'Iconic departures corridor lightboxes, security-check digital screens, and external aerobridge wraps at Mumbai’s award-winning Terminal 2. Direct high-frequency influence on Western India’s top corporate executives and luxury consumers.'
  },
  {
    id: 'svc_airport_bengaluru',
    name: 'Bengaluru Airport Advertising',
    type: 'Airport',
    genre: 'Airport',
    sub_type: 'Terminal 1 & Terminal 2 Tech Hub Displays',
    chain_or_brand: 'Kempegowda International Airport',
    audience_metric: '3.4M+ Monthly Passengers • High Tech Professional Share',
    min_spend: 60000,
    price: 150000,
    rating: 4.9,
    popularity: 96,
    status: 'Active',
    dims: '28 × 12 ft High-Lumen Lightboxes & Digital Totems',
    durations: '1 Month, 3 Months, 6 Months, 12 Months',
    cities: 'Bengaluru',
    image: 'https://images.unsplash.com/photo-1508873696983-2df5293cb32f?q=80&w=800&auto=format&fit=crop',
    description: 'High-definition digital totems and grand arrival hall displays across Kempegowda Terminal 1 and the iconic Terminal 2 garden terminal. Prime connection point to India’s leading tech founders, venture capitalists, and global business travelers.'
  },
  {
    id: 'svc_airport_hyderabad',
    name: 'Hyderabad Airport Advertising',
    type: 'Airport',
    genre: 'Airport',
    sub_type: 'Main Passenger Terminal Static & Digital Hub',
    chain_or_brand: 'Rajiv Gandhi International Airport',
    audience_metric: '2.2M+ Monthly Passengers • Pharma & IT Hub',
    min_spend: 50000,
    price: 120000,
    rating: 4.8,
    popularity: 93,
    status: 'Active',
    dims: '20 × 10 ft Backlit Displays & Departure Gates',
    durations: '1 Month, 3 Months, 6 Months, 12 Months',
    cities: 'Hyderabad',
    image: 'https://images.unsplash.com/photo-1530521954074-e64f6810b32d?q=80&w=800&auto=format&fit=crop',
    description: 'Strategic boarding gate signage, duty-free retail corridor pillars, and arrival reclaim carousels at RGIA Shamshabad. Premium visual real estate reaching leaders across the pharmaceutical, biotechnology, and enterprise software sectors.'
  },
  {
    id: 'svc_airport_chennai',
    name: 'Chennai Airport Advertising',
    type: 'Airport',
    genre: 'Airport',
    sub_type: 'Domestic & International Terminal Lightboxes',
    chain_or_brand: 'Chennai International Airport',
    audience_metric: '1.8M+ Monthly Passengers • Industrial & Trade Gateway',
    min_spend: 45000,
    price: 110000,
    rating: 4.7,
    popularity: 90,
    status: 'Active',
    dims: '24 × 10 ft Backlit Displays & Security Hall Banners',
    durations: '1 Month, 3 Months, 6 Months, 12 Months',
    cities: 'Chennai',
    image: 'https://images.unsplash.com/photo-1578637387939-43c525550085?q=80&w=800&auto=format&fit=crop',
    description: 'Prominent security check entrance displays, baggage reclaim pillars, and arrivals concourse lightboxes across modern terminals at Chennai Airport. Comprehensive coverage targeting South India’s automotive and heavy manufacturing corporate leaders.'
  },
  {
    id: 'svc_airport_kolkata',
    name: 'Kolkata Airport Advertising',
    type: 'Airport',
    genre: 'Airport',
    sub_type: 'Integrated Terminal Static & Digital Media',
    chain_or_brand: 'Netaji Subhash Chandra Bose International Airport',
    audience_metric: '1.6M+ Monthly Passengers • Eastern India Commercial Hub',
    min_spend: 40000,
    price: 98000,
    rating: 4.7,
    popularity: 89,
    status: 'Active',
    dims: '20 × 8 ft Backlit Panels & Arrival Hall Gantries',
    durations: '1 Month, 3 Months, 6 Months, 12 Months',
    cities: 'Kolkata',
    image: 'https://images.unsplash.com/photo-1569154941061-e231b4725ef1?q=80&w=800&auto=format&fit=crop',
    description: 'High-impact boarding gate overhead displays, aerobridge wraps, and grand arrivals hall static banners at Kolkata’s integrated terminal. The primary aviation hub linking East and North-East India to major metropolitan commercial centers.'
  },
  {
    id: 'svc_airport_pune',
    name: 'Pune Airport Advertising',
    type: 'Airport',
    genre: 'Airport',
    sub_type: 'New Integrated Terminal Media Network',
    chain_or_brand: 'Pune International Airport',
    audience_metric: '950,000+ Monthly Passengers • Manufacturing & Tech Leaders',
    min_spend: 35000,
    price: 85000,
    rating: 4.8,
    popularity: 91,
    status: 'Active',
    dims: '18 × 8 ft Backlit Lightboxes & Departures Pillar Wraps',
    durations: '1 Month, 3 Months, 6 Months, 12 Months',
    cities: 'Pune',
    image: 'https://images.unsplash.com/photo-1512100356356-de1b84283e18?q=80&w=800&auto=format&fit=crop',
    description: 'Modern departures concourse lightboxes and arrivals baggage reclaim panels across Pune’s state-of-the-art new integrated terminal. Captures affluent automotive engineers, IT professionals, and frequent flyers travelling between key industrial hubs.'
  },
  {
    id: 'svc_airport_ahmedabad',
    name: 'Ahmedabad Airport Advertising',
    type: 'Airport',
    genre: 'Airport',
    sub_type: 'Terminal 1 & Terminal 2 Business Concourse Displays',
    chain_or_brand: 'Sardar Vallabhbhai Patel International Airport',
    audience_metric: '1.1M+ Monthly Passengers • Business & Entrepreneur Hub',
    min_spend: 38000,
    price: 92000,
    rating: 4.8,
    popularity: 92,
    status: 'Active',
    dims: '20 × 10 ft Static Lightboxes & Digital Totem Displays',
    durations: '1 Month, 3 Months, 6 Months, 12 Months',
    cities: 'Ahmedabad',
    image: 'https://images.unsplash.com/photo-1520437358207-323b43b50729?q=80&w=800&auto=format&fit=crop',
    description: 'High-visibility security check panels, departure lounge static banners, and baggage claim displays at SVPIA Ahmedabad. Delivers unparalleled reach across Western India’s wealthiest trading communities, textile magnates, and industrial entrepreneurs.'
  },
  {
    id: 'svc_airport_goa',
    name: 'Goa Airport Advertising',
    type: 'Airport',
    genre: 'Airport',
    sub_type: 'Dabolim & Mopa (Manohar) Leisure Gateway Displays',
    chain_or_brand: 'Goa International Airports (GOI & GOX)',
    audience_metric: '880,000+ Monthly High-Spender Tourists & Lifestyle Flyers',
    min_spend: 42000,
    price: 105000,
    rating: 4.9,
    popularity: 94,
    status: 'Active',
    dims: '24 × 10 ft Static Lightboxes & Arrival Reclaim Wraps',
    durations: '1 Month, 3 Months, 6 Months, 12 Months',
    cities: 'Goa',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=800&auto=format&fit=crop',
    description: 'Prime arrivals hall lightboxes, baggage belt wraps, and departure gate signage across both Dabolim and Manohar International (Mopa) airports. Reach relaxed, high-disposable-income leisure tourists, wedding parties, and young urban professionals on holiday.'
  },

  // --- CINEMA (Expanded with Generic Multiplex Chain) ---
  {
    id: 'svc_cinema_pvr',
    name: 'PVR INOX Multiplex Cinema Ads',
    type: 'Cinema',
    genre: 'Cinema',
    sub_type: 'On-Screen Video & Slide Ads',
    chain_or_brand: 'PVR INOX',
    audience_metric: '280 Seats/Screen • 4.2L+ Monthly Footfall',
    min_spend: 11400,
    price: 32000,
    rating: 4.9,
    popularity: 97,
    status: 'Active',
    dims: '2K / 4K DCP • 10–30s Spots',
    durations: '1 Week, 2 Weeks, 1 Month, 3 Months',
    cities: 'Mumbai, Bengaluru, Delhi NCR, Hyderabad, Pune',
    image: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?q=80&w=800&auto=format&fit=crop',
    description: 'Captive, high-impact cinema advertising across premium PVR and INOX audi screens. On-screen slides, Dolby Atmos cinema video commercials, and lobby standees during blockbuster releases.'
  },
  {
    id: 'svc_cinema_cinepolis',
    name: 'Cinepolis Fun Republic On-Screen Ads',
    type: 'Cinema',
    genre: 'Cinema',
    sub_type: 'Digital Screen & Slide Ad',
    chain_or_brand: 'Cinépolis',
    audience_metric: '252 Seats/Screen • High Affluent Youth Dwell',
    min_spend: 6080,
    price: 18500,
    rating: 4.8,
    popularity: 91,
    status: 'Active',
    dims: 'Full Cinema Screen • High Lumen DCP',
    durations: '1 Week, 2 Weeks, 1 Month',
    cities: 'Mumbai, Bengaluru, Pune, Delhi NCR',
    image: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?q=80&w=800&auto=format&fit=crop',
    description: 'High-visibility digital slides and video commercials before movie trailers and interval. Reach young, tech-savvy cinema-goers across premier Cinepolis locations.'
  },
  {
    id: 'svc_cinema_multiplex_chain',
    name: 'Multiplex Chain Cinema Advertising',
    type: 'Cinema',
    genre: 'Cinema',
    sub_type: 'On-Screen Slides & Video Commercials',
    chain_or_brand: 'National Multiplex Cinema Network',
    audience_metric: '220 Seats/Screen • 3.1L+ Monthly Footfall',
    min_spend: 8500,
    price: 24000,
    rating: 4.7,
    popularity: 89,
    status: 'Active',
    dims: '2K / 4K Digital Cinema DCP • 10–30s Spots',
    durations: '1 Week, 2 Weeks, 1 Month, 3 Months',
    cities: 'Mumbai, Bengaluru, Delhi NCR, Pune, Hyderabad, Kolkata',
    image: 'https://images.unsplash.com/photo-1595769816263-9b910be24d5f?q=80&w=800&auto=format&fit=crop',
    description: 'High-impact on-screen slide and video advertising across regional and national multiplex screens. Captive audiences, Dolby surround sound, and interval lobby branding in high-traffic commercial entertainment hubs.'
  },

  // --- OUTDOOR (Per-City Highway & Arterial Listings) ---
  {
    id: 'svc_outdoor_mumbai',
    name: 'Mumbai Outdoor Advertising',
    type: 'Outdoor',
    genre: 'Outdoor',
    sub_type: 'Large Format Unipole & Hoarding',
    chain_or_brand: 'Mumbai Arterial Network',
    audience_metric: '42 Prime Sites • 1.8M+ Weekly Vehicular Reach',
    min_spend: 45000,
    price: 120000,
    rating: 4.9,
    popularity: 97,
    status: 'Active',
    dims: '40 × 20 ft & 60 × 20 ft Front-lit Unipoles',
    durations: '1 Month, 3 Months, 6 Months, 12 Months',
    cities: 'Mumbai',
    image: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?q=80&w=800&auto=format&fit=crop',
    description: 'High-impact large-format unipoles and cantilever hoardings across Western Express Highway, Eastern Freeway, and Bandra-Worli Sea Link approaches. Premium front-lit illumination ensuring continuous 24/7 visibility for marquee brands.'
  },
  {
    id: 'svc_outdoor_delhi',
    name: 'Delhi NCR Outdoor Advertising',
    type: 'Outdoor',
    genre: 'Outdoor',
    sub_type: 'Highway Unipole & Expressway Gantry',
    chain_or_brand: 'Delhi NCR Arterial Network',
    audience_metric: '56 Prime Sites • 2.2M+ Weekly Commuters',
    min_spend: 40000,
    price: 110000,
    rating: 4.9,
    popularity: 96,
    status: 'Active',
    dims: '48 × 20 ft Front-lit Unipoles & Gantries',
    durations: '1 Month, 3 Months, 6 Months, 12 Months',
    cities: 'Delhi NCR',
    image: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?q=80&w=800&auto=format&fit=crop',
    description: 'Strategic highway unipoles and expressway gantries along NH-48, Cyber City junction, DND Flyway, and Ring Road arterial corridors. Engineered for high dwell time and maximum brand prestige in the capital region.'
  },
  {
    id: 'svc_outdoor_bengaluru',
    name: 'Bengaluru Outdoor Advertising',
    type: 'Outdoor',
    genre: 'Outdoor',
    sub_type: 'Arterial Corridor Billboard & Unipole',
    chain_or_brand: 'Bengaluru Highway Network',
    audience_metric: '38 Prime Sites • 1.4M+ Weekly Tech Commuters',
    min_spend: 35000,
    price: 90000,
    rating: 4.8,
    popularity: 94,
    status: 'Active',
    dims: '35 × 15 ft & 40 × 20 ft Front-lit Billboards',
    durations: '1 Month, 3 Months, 6 Months, 12 Months',
    cities: 'Bengaluru',
    image: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?q=80&w=800&auto=format&fit=crop',
    description: 'High-density tech corridor hoardings along Outer Ring Road (ORR), Electronic City flyover, and Hebbal Airport Expressway. Positioned at key bottleneck junctions for sustained eye-level recall among affluent IT professionals.'
  },
  {
    id: 'svc_outdoor_hyderabad',
    name: 'Hyderabad Outdoor Advertising',
    type: 'Outdoor',
    genre: 'Outdoor',
    sub_type: 'Expressway Gantry & Unipole',
    chain_or_brand: 'Hyderabad Arterial Network',
    audience_metric: '30 Prime Sites • 1.1M+ Weekly Vehicular Impressions',
    min_spend: 30000,
    price: 75000,
    rating: 4.8,
    popularity: 92,
    status: 'Active',
    dims: '40 × 15 ft Unipoles & Gantry Hoardings',
    durations: '1 Month, 3 Months, 6 Months, 12 Months',
    cities: 'Hyderabad',
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?q=80&w=800&auto=format&fit=crop',
    description: 'Prominent arterial unipoles covering Hitec City, Gachibowli Financial District, and PVNR Elevated Expressway. Exceptional line-of-sight exposure targeting enterprise decision-makers and urban consumers.'
  },
  {
    id: 'svc_outdoor_pune',
    name: 'Pune Outdoor Advertising',
    type: 'Outdoor',
    genre: 'Outdoor',
    sub_type: 'Expressway Hoarding & Arterial Billboard',
    chain_or_brand: 'Pune Arterial Network',
    audience_metric: '24 Prime Sites • 850,000+ Weekly Vehicular Reach',
    min_spend: 25000,
    price: 65000,
    rating: 4.7,
    popularity: 90,
    status: 'Active',
    dims: '30 × 15 ft & 40 × 20 ft Billboards',
    durations: '1 Month, 3 Months, 6 Months, 12 Months',
    cities: 'Pune',
    image: 'https://images.unsplash.com/photo-1567157577867-05ccb1388e66?q=80&w=800&auto=format&fit=crop',
    description: 'Prime outdoor billboard positions across Mumbai-Pune Expressway exit, Baner Road, Senapati Bapat Road, and Koregaon Park arterial connectors. High frequency coverage across Pune’s fastest growing commercial corridors.'
  },

  // --- TRANSIT (Metro, Local Train & Bus Shelters by City) ---
  {
    id: 'svc_transit_delhi_metro',
    name: 'Delhi Metro Advertising',
    type: 'Transit',
    genre: 'Transit',
    sub_type: 'Concourse, PSD & Train Wrap',
    chain_or_brand: 'Delhi Metro Rail Network',
    audience_metric: '3.2M+ Daily Commuters across Yellow & Blue Lines',
    min_spend: 20000,
    price: 55000,
    rating: 4.9,
    popularity: 98,
    status: 'Active',
    dims: '20 × 10 ft Static Panels & Digital Displays',
    durations: '1 Week, 2 Weeks, 1 Month, 3 Months, 6 Months, 12 Months',
    cities: 'Delhi NCR',
    image: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?q=80&w=800&auto=format&fit=crop',
    description: 'Full-station concourse branding, ticket counter panels, platform screen doors, and exterior train wraps across DMRC interchanges. Unrivaled frequency and captive audience reach in North India’s busiest mass transit system.'
  },
  {
    id: 'svc_transit_mumbai_metro',
    name: 'Mumbai Metro Advertising',
    type: 'Transit',
    genre: 'Transit',
    sub_type: 'Station Branding & Metro Train Wraps',
    chain_or_brand: 'Mumbai Metro Transit System',
    audience_metric: '1.8M+ Daily Commuters across Lines 1, 2A & 7',
    min_spend: 18000,
    price: 50000,
    rating: 4.8,
    popularity: 95,
    status: 'Active',
    dims: '15 × 8 ft Backlit Panels & In-Train Branding',
    durations: '1 Week, 2 Weeks, 1 Month, 3 Months, 6 Months, 12 Months',
    cities: 'Mumbai',
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?q=80&w=800&auto=format&fit=crop',
    description: 'Modern transit advertising inside metro trains and elevated station concourses along Andheri-Ghatkopar and Western Express corridors. High visibility among upwardly mobile daily corporate commuters.'
  },
  {
    id: 'svc_transit_mumbai_local_train',
    name: 'Mumbai Local Train Advertising',
    type: 'Transit',
    genre: 'Transit',
    sub_type: 'Local Train Wraps & FOB Hoardings',
    chain_or_brand: 'Mumbai Suburban Railway',
    audience_metric: '7.5M+ Mass Daily Passengers across Central & Western Lines',
    min_spend: 25000,
    price: 65000,
    rating: 4.9,
    popularity: 99,
    status: 'Active',
    dims: 'Train Compartment Posters & 30 × 10 ft Station Hoardings',
    durations: '1 Month, 3 Months, 6 Months, 12 Months',
    cities: 'Mumbai',
    image: 'https://images.unsplash.com/photo-1565019011521-b0575cbb57c8?q=80&w=800&auto=format&fit=crop',
    description: 'The undisputed lifeline of Mumbai. Station platform walls, foot-over-bridge banners, and full exterior/interior suburban train branding reaching millions of daily travelers with unbeatable mass penetration.'
  },
  {
    id: 'svc_transit_bengaluru_metro',
    name: 'Bengaluru Namma Metro Advertising',
    type: 'Transit',
    genre: 'Transit',
    sub_type: 'Station Pillars & Concourse Panels',
    chain_or_brand: 'Namma Metro Network',
    audience_metric: '850,000+ Daily Tech & White-Collar Commuters',
    min_spend: 16000,
    price: 48000,
    rating: 4.8,
    popularity: 93,
    status: 'Active',
    dims: '12 × 6 ft Backlit Lightboxes & Pillar Wraps',
    durations: '1 Week, 2 Weeks, 1 Month, 3 Months, 6 Months',
    cities: 'Bengaluru',
    image: 'https://images.unsplash.com/photo-1555680202-c86f0e12f086?q=80&w=800&auto=format&fit=crop',
    description: 'Prime station presence along the Purple and Green Metro corridors connecting Indiranagar, MG Road, and Whitefield. Captures tech-forward professionals and students during peak business commute hours.'
  },
  {
    id: 'svc_transit_delhi_bus_shelters',
    name: 'Delhi NCR Bus Shelter Network',
    type: 'Transit',
    genre: 'Transit',
    sub_type: 'Bus Queue Shelter Mupis',
    chain_or_brand: 'Delhi NCR Transit Shelters',
    audience_metric: '65,000+ Daily Eye-Level Vehicular Views / Shelter',
    min_spend: 12000,
    price: 22000,
    rating: 4.7,
    popularity: 88,
    status: 'Active',
    dims: '6 × 4 ft Double-Sided Backlit Mupi',
    durations: '2 Weeks, 1 Month, 3 Months, 6 Months',
    cities: 'Delhi NCR',
    image: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?q=80&w=800&auto=format&fit=crop',
    description: 'Eye-level illuminated bus queue shelter displays spanning major arterial roads in Central Delhi, South Delhi, Noida, and Gurugram. High dwell time and street-level repetition targeting urban shoppers and motorists.'
  },
  {
    id: 'svc_transit_mumbai_bus_shelters',
    name: 'Mumbai Transit Shelter Network',
    type: 'Transit',
    genre: 'Transit',
    sub_type: 'Bus Queue Shelter Mupis',
    chain_or_brand: 'Mumbai Municipal Bus Shelters',
    audience_metric: '80,000+ Daily Eye-Level Views / Location',
    min_spend: 14000,
    price: 26000,
    rating: 4.7,
    popularity: 89,
    status: 'Active',
    dims: '6 × 4 ft Backlit Street Mupis',
    durations: '2 Weeks, 1 Month, 3 Months, 6 Months',
    cities: 'Mumbai',
    image: 'https://images.unsplash.com/photo-1509749837427-ac94a2553d0e?q=80&w=800&auto=format&fit=crop',
    description: 'Illuminated bus shelter network deployed across South Mumbai, Bandra, Juhu, and suburban commercial high-streets. Continuous pedestrian and vehicular impressions with superior night illumination.'
  },
  {
    id: 'svc_transit_bengaluru_bus_shelters',
    name: 'Bengaluru Bus Shelter Network',
    type: 'Transit',
    genre: 'Transit',
    sub_type: 'Bus Queue Shelter Mupis',
    chain_or_brand: 'Bengaluru BMTC Shelter Network',
    audience_metric: '55,000+ Daily Eye-Level Views / Shelter',
    min_spend: 10000,
    price: 20000,
    rating: 4.7,
    popularity: 87,
    status: 'Active',
    dims: '6 × 4 ft Illuminated Backlit Displays',
    durations: '2 Weeks, 1 Month, 3 Months, 6 Months',
    cities: 'Bengaluru',
    image: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?q=80&w=800&auto=format&fit=crop',
    description: 'Curated clusters of backlit bus shelters across Koramangala, Indiranagar, CBD, and Outer Ring Road junctions. Delivers continuous roadside frequency and localized brand resonance.'
  },

  // --- MALL / RETAIL (City-Named Premium Mall Networks) ---
  {
    id: 'svc_retail_bengaluru_malls',
    name: 'Bengaluru Premium Mall Network',
    type: 'Retail',
    genre: 'Retail',
    sub_type: 'Atrium Drops, Pillar Wraps & Standees',
    chain_or_brand: 'Bengaluru Premium Shopping Centers',
    audience_metric: '4.2L+ High-Spender Weekend Footfall',
    min_spend: 20000,
    price: 58000,
    rating: 4.8,
    popularity: 88,
    status: 'Active',
    dims: 'Multi-tier Atrium Drop Banners & LED Kiosks',
    durations: '1 Week, 2 Weeks, 1 Month, 3 Months',
    cities: 'Bengaluru',
    image: 'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?q=80&w=800&auto=format&fit=crop',
    description: 'Atrium hanging banners, entrance archways, elevator door wraps, and experiential zones in Bengaluru’s leading luxury and lifestyle shopping centers. Unmatched point-of-sale influence for premium consumer, fashion, and electronics brands.'
  },
  {
    id: 'svc_retail_mumbai_malls',
    name: 'Mumbai Premium Mall Network',
    type: 'Retail',
    genre: 'Retail',
    sub_type: 'Atrium Banners & Digital Totems',
    chain_or_brand: 'Mumbai Prime Retail Malls',
    audience_metric: '5.5L+ Weekend Shopper Footfall',
    min_spend: 25000,
    price: 68000,
    rating: 4.9,
    popularity: 92,
    status: 'Active',
    dims: 'Atrium Drops, Escalator Glass Branding & Standees',
    durations: '1 Week, 2 Weeks, 1 Month, 3 Months',
    cities: 'Mumbai',
    image: 'https://images.unsplash.com/photo-1567449303078-57ad995bd302?q=80&w=800&auto=format&fit=crop',
    description: 'High-impact retail branding across prime South Mumbai, BKC, and Suburban luxury destination malls. Direct access to affluent urban families and leisure shoppers during their active purchasing mindset.'
  },
  {
    id: 'svc_retail_delhi_malls',
    name: 'Delhi NCR Mall Network',
    type: 'Retail',
    genre: 'Retail',
    sub_type: 'Atrium Drops & Food Court Branding',
    chain_or_brand: 'Delhi NCR Grade-A Shopping Centers',
    audience_metric: '6.0L+ Weekly Lifestyle Footfall',
    min_spend: 22000,
    price: 62000,
    rating: 4.8,
    popularity: 90,
    status: 'Active',
    dims: 'Grand Atrium Drops & Digital Facade Displays',
    durations: '1 Week, 2 Weeks, 1 Month, 3 Months',
    cities: 'Delhi NCR',
    image: 'https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?q=80&w=800&auto=format&fit=crop',
    description: 'Dominant visual displays, grand atrium drops, and food-court table wraps across top-tier malls in Saket, Vasant Kunj, Noida, and Gurugram. Proven driver of walk-ins, festive sales, and retail brand launch hype.'
  },

  // --- STREET / KIOSK (Per-City Kiosk Networks) ---
  {
    id: 'svc_kiosk_bengaluru',
    name: 'Bengaluru Street Kiosks',
    type: 'Street Furniture',
    genre: 'Street Furniture',
    sub_type: 'Double-Sided Backlit Pole Kiosks',
    chain_or_brand: 'Bengaluru Arterial Road Kiosks',
    audience_metric: '90,000+ Vehicles Daily / 10-Pole Corridor',
    min_spend: 12000,
    price: 15000,
    rating: 4.6,
    popularity: 80,
    status: 'Active',
    dims: '8 × 4 ft • Double-Sided Backlit',
    durations: '1 Month, 3 Months, 6 Months',
    cities: 'Bengaluru',
    image: 'https://images.unsplash.com/photo-1444723121867-7a241cacace9?q=80&w=800&auto=format&fit=crop',
    description: 'Consecutive double-sided backlit kiosks along CBD, MG Road, 100ft Indiranagar, and HSR Layout commercial corridors. Repetitive frequency guarantees subconscious brand recall among daily motorists and shoppers.'
  },
  {
    id: 'svc_kiosk_delhi',
    name: 'Delhi NCR Street Kiosks',
    type: 'Street Furniture',
    genre: 'Street Furniture',
    sub_type: 'Double-Sided Backlit Street Poles',
    chain_or_brand: 'Delhi NCR Municipal Pole Network',
    audience_metric: '1.1L+ Vehicles Daily / Arterial Stretch',
    min_spend: 14000,
    price: 16500,
    rating: 4.6,
    popularity: 82,
    status: 'Active',
    dims: '8 × 4 ft • High-Illumination Backlit Kiosks',
    durations: '1 Month, 3 Months, 6 Months',
    cities: 'Delhi NCR',
    image: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?q=80&w=800&auto=format&fit=crop',
    description: 'Sequential street pole branding along key avenues in Central Delhi, Ring Road, and prime Gurugram connectors. Ideal for hyperlocal real estate launches, healthcare chains, and retail store openings.'
  },
  {
    id: 'svc_kiosk_mumbai',
    name: 'Mumbai Street Kiosks',
    type: 'Street Furniture',
    genre: 'Street Furniture',
    sub_type: 'Arterial Backlit Street Kiosks',
    chain_or_brand: 'Mumbai Arterial Pole Network',
    audience_metric: '1.25L+ Daily Commuter Density / Sector',
    min_spend: 15000,
    price: 18000,
    rating: 4.7,
    popularity: 84,
    status: 'Active',
    dims: '8 × 4 ft • Double-Sided Marine-Grade Backlit',
    durations: '1 Month, 3 Months, 6 Months',
    cities: 'Mumbai',
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=800&auto=format&fit=crop',
    description: 'Illuminated pole kiosk runs across Marine Drive, Linking Road Bandra, and Andheri Link Road. High-density street furniture ensuring inescapable frequency for youth and lifestyle brands.'
  },

  // --- BTL ACTIVATIONS (Per Activation Format) ---
  {
    id: 'svc_btl_stadium',
    name: 'Stadium & Sports Arena BTL Activations',
    type: 'BTL',
    genre: 'BTL',
    sub_type: 'Experiential Fan Zones & Concourse Booths',
    chain_or_brand: 'Arena Fan Engagement Network',
    audience_metric: '45,000+ High-Energy Fans / Match Day',
    min_spend: 50000,
    price: 140000,
    rating: 4.9,
    popularity: 95,
    status: 'Active',
    dims: '20 × 20 ft Interactive Fan Booth + Brand Ambassadors',
    durations: '1 Weekend, 1 Match Day, Multi-Match Series',
    cities: 'Mumbai, Delhi NCR, Bengaluru, Hyderabad, Chennai, Kolkata, Ahmedabad',
    image: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=800&auto=format&fit=crop',
    description: 'Immersive brand pavilions, interactive gaming zones, and direct merchandise sampling during major cricket and sports matches. Connect with impassioned, high-energy audiences in a memorable experiential setting.'
  },
  {
    id: 'svc_btl_college_fest',
    name: 'College Fest & Campus BTL Activations',
    type: 'BTL',
    genre: 'BTL',
    sub_type: 'Campus Canopies & Youth Engagement Stalls',
    chain_or_brand: 'Campus Activation Network',
    audience_metric: '15,000+ Gen Z & Young Adult Footfall / Fest',
    min_spend: 18000,
    price: 42000,
    rating: 4.8,
    popularity: 90,
    status: 'Active',
    dims: '12 × 12 ft Canopy Setup + Audio & Promoters',
    durations: '2-3 Days Fest, 1 Week Tour',
    cities: 'Delhi NCR, Mumbai, Bengaluru, Pune, Hyderabad, Chennai',
    image: 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?q=80&w=800&auto=format&fit=crop',
    description: 'On-ground interactive stalls, product sampling kiosks, and contest booths at premier university fests and management institutes. Direct peer-to-peer engagement and app download drives with India’s Gen Z trendsetters.'
  },
  {
    id: 'svc_btl_rwa_society',
    name: 'RWA & Residential Society Activations',
    type: 'BTL',
    genre: 'BTL',
    sub_type: 'Township Canopies & Door-to-Door Engagement',
    chain_or_brand: 'Premium Gated Societies Network',
    audience_metric: '3,500+ Qualified High-Net-Worth Households / Complex',
    min_spend: 15000,
    price: 35000,
    rating: 4.8,
    popularity: 88,
    status: 'Active',
    dims: '10 × 10 ft Clubhouse Canopy + Promoters & Lead App',
    durations: '1 Weekend, 2 Weekends, 1 Month Package',
    cities: 'Bengaluru, Mumbai, Delhi NCR, Hyderabad, Pune',
    image: 'https://images.unsplash.com/photo-1511578314322-379afb476865?q=80&w=800&auto=format&fit=crop',
    description: 'Exclusive weekend pop-ups, vehicle test-drive experiences, and product trial counters inside top gated communities and townships. High-trust environment generating verified, affluent family leads for D2C and premium services.'
  },

  // --- NEWSPAPER / PRINT (Category & Language Press) ---
  {
    id: 'svc_print_english_daily',
    name: 'English Daily Newspaper Advertising',
    type: 'Print',
    genre: 'Print',
    sub_type: 'Full Page Jacket & Display Ads',
    chain_or_brand: 'National English Daily Press',
    audience_metric: '1.2M+ Verified Daily Circulation • High SEC-A Readers',
    min_spend: 35000,
    price: 95000,
    rating: 4.8,
    popularity: 91,
    status: 'Active',
    dims: 'Full Page (33 × 52 cm) / Half Page / Front Page Jacket',
    durations: '1 Insertion, 3 Insertions, 6 Insertions',
    cities: 'Delhi NCR, Mumbai, Bengaluru, Hyderabad, Chennai, Kolkata, Pune',
    image: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?q=80&w=800&auto=format&fit=crop',
    description: 'Front page jackets, display advertisements, and innovative bookmark wraps in premier national English dailies. Maximum corporate credibility and instant nationwide recall for flagship product and public announcement campaigns.'
  },
  {
    id: 'svc_print_regional_press',
    name: 'Regional Language Press Advertising',
    type: 'Print',
    genre: 'Print',
    sub_type: 'Regional Edition Display & Classifieds',
    chain_or_brand: 'Leading Regional Press Network',
    audience_metric: '2.4M+ Combined Regional Readership',
    min_spend: 20000,
    price: 55000,
    rating: 4.7,
    popularity: 86,
    status: 'Active',
    dims: 'Full Page / Half Page / Quarter Page Display',
    durations: '1 Insertion, 3 Insertions, 6 Insertions',
    cities: 'Mumbai, Pune, Bengaluru, Hyderabad, Ahmedabad, Kolkata',
    image: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?q=80&w=800&auto=format&fit=crop',
    description: 'Deep-penetration print advertisements in top Hindi, Marathi, Kannada, Telugu, Gujarati, and Bengali dailies. Hyperlocal community trust and wide grassroots reach across tier-1 and tier-2 urban clusters.'
  },
  {
    id: 'svc_print_financial_daily',
    name: 'Financial & Business Daily Advertising',
    type: 'Print',
    genre: 'Print',
    sub_type: 'Financial Page Display & Notice Ads',
    chain_or_brand: 'Financial & Economic Press Network',
    audience_metric: '650,000+ Business Leaders, Investors & CXOs',
    min_spend: 28000,
    price: 78000,
    rating: 4.8,
    popularity: 88,
    status: 'Active',
    dims: 'Half Page / Strip Ad / Full Page Financial Ad',
    durations: '1 Insertion, 3 Insertions, 6 Insertions',
    cities: 'Delhi NCR, Mumbai, Bengaluru, Hyderabad',
    image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?q=80&w=800&auto=format&fit=crop',
    description: 'Targeted business display ads, investor notices, and quarter-page corporate updates in leading pink-paper economic dailies. Direct visual access to CFOs, founders, retail investors, and policy stakeholders.'
  },

  // --- DIGITAL / DOOH (Digital LED Walls) ---
  {
    id: 'svc_led',
    name: 'Tech Park & Mall Digital DOOH Screens',
    type: 'Digital',
    genre: 'Digital',
    sub_type: 'Digital DOOH LED Wall',
    chain_or_brand: 'Corporate Parks & Malls',
    audience_metric: '1.8L+ Daily Tech Professionals & Shoppers',
    min_spend: 20000,
    price: 88000,
    rating: 4.9,
    popularity: 92,
    status: 'Active',
    dims: 'P6 LED • 15-sec loop, 120 plays/day',
    durations: '1 Week, 2 Weeks, 1 Month, 3 Months',
    cities: 'Bengaluru, Mumbai, Delhi NCR, Hyderabad',
    image: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?q=80&w=800&auto=format&fit=crop',
    description: 'Programmatic-grade LED walls at Cyber City, BKC, Manyata Tech Park & Whitefield. Day-parting, live data feeds and instant creative swaps. 120 spots/day guaranteed.'
  }
];

export const initialLocations = [
  {
    id: 'loc_1',
    name: 'Central Metro Hub — Concourse',
    city: 'New Delhi',
    zone: 'Central',
    footfall: 250000,
    size: '20 × 10 ft Backlit ×6',
    status: 'Occupied',
    image: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'loc_2',
    name: 'Airport T3 Arrival Corridor',
    city: 'New Delhi',
    zone: 'South',
    footfall: 92000,
    size: '30 × 12 ft Banner ×4',
    status: 'Occupied',
    image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'loc_3',
    name: 'NH-48 Unipole — Cyber City Cut',
    city: 'Gurugram',
    zone: 'South',
    footfall: 180000,
    size: '48 × 20 ft Unipole',
    status: 'Occupied',
    image: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'loc_4',
    name: 'MG Road Bus Shelters (12 Units)',
    city: 'Bengaluru',
    zone: 'Central',
    footfall: 85000,
    size: '6 × 4 ft Mupi ×12',
    status: 'Available',
    image: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'loc_5',
    name: 'Phoenix Mall — Grand Atrium',
    city: 'Mumbai',
    zone: 'West',
    footfall: 65000,
    size: 'Atrium + Facade',
    status: 'Available',
    image: 'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'loc_6',
    name: 'CST Concourse Hoarding Wall',
    city: 'Mumbai',
    zone: 'South',
    footfall: 410000,
    size: '40 × 20 ft ×3',
    status: 'Occupied',
    image: 'https://images.unsplash.com/photo-1565019011521-b0575cbb57c8?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'loc_7',
    name: 'Cyber Hub LED Wall',
    city: 'Gurugram',
    zone: 'South',
    footfall: 48000,
    size: 'P6 LED 24×12 ft',
    status: 'Occupied',
    image: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'loc_8',
    name: 'Marine Drive Pole Cluster (24)',
    city: 'Mumbai',
    zone: 'South',
    footfall: 120000,
    size: '8×4 ft ×24 poles',
    status: 'Available',
    image: 'https://images.unsplash.com/photo-1444723121867-7a241cacace9?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'loc_9',
    name: 'Rajiv Chowk Metro Gates',
    city: 'New Delhi',
    zone: 'Central',
    footfall: 320000,
    size: 'Gate wraps + PSD',
    status: 'Occupied',
    image: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'loc_10',
    name: 'Hitech City LED — Madhapur',
    city: 'Hyderabad',
    zone: 'West',
    footfall: 55000,
    size: 'P6 LED 20×10 ft',
    status: 'Available',
    image: 'https://images.unsplash.com/photo-1444653614773-995cb1ef9efa?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'loc_11',
    name: 'Yamuna Expressway Gantry',
    city: 'Noida',
    zone: 'East',
    footfall: 95000,
    size: '60 × 15 ft Gantry',
    status: 'Available',
    image: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'loc_12',
    name: 'Airport Express Metro — Pillars',
    city: 'New Delhi',
    zone: 'South',
    footfall: 110000,
    size: 'Pillar wraps ×18',
    status: 'Maintenance',
    image: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?q=80&w=800&auto=format&fit=crop'
  }
];

export const initialServiceLocations = [
  { id: 'sl1', service_id: 'svc_transit_delhi_metro', location_id: 'loc_1' },
  { id: 'sl2', service_id: 'svc_transit_delhi_metro', location_id: 'loc_9' },
  { id: 'sl3', service_id: 'svc_transit_delhi_metro', location_id: 'loc_12' },
  { id: 'sl4', service_id: 'svc_transit_bengaluru_bus_shelters', location_id: 'loc_4' },
  { id: 'sl5', service_id: 'svc_transit_mumbai_bus_shelters', location_id: 'loc_8' },
  { id: 'sl6', service_id: 'svc_airport_delhi', location_id: 'loc_2' },
  { id: 'sl7', service_id: 'svc_outdoor_delhi', location_id: 'loc_3' },
  { id: 'sl8', service_id: 'svc_outdoor_delhi', location_id: 'loc_11' },
  { id: 'sl9', service_id: 'svc_retail_mumbai_malls', location_id: 'loc_5' },
  { id: 'sl10', service_id: 'svc_transit_mumbai_local_train', location_id: 'loc_6' },
  { id: 'sl11', service_id: 'svc_led', location_id: 'loc_7' },
  { id: 'sl12', service_id: 'svc_led', location_id: 'loc_10' },
  { id: 'sl13', service_id: 'svc_kiosk_mumbai', location_id: 'loc_8' },
  { id: 'sl14', service_id: 'svc_kiosk_bengaluru', location_id: 'loc_4' }
];

export const initialCampaigns = [
  {
    id: 'cp1',
    title: 'Nike — Just Do It Takeover',
    client: 'Nike India',
    service_id: 'svc_outdoor_delhi',
    location_id: 'loc_3',
    start_date: '2026-08-01',
    end_date: '2026-11-01',
    budget: 680000,
    status: 'Live',
    artwork: 'https://images.unsplash.com/photo-1444653614773-995cb1ef9efa?q=80&w=800&auto=format&fit=crop',
    notes: 'Front-lit unipole + night patrol'
  },
  {
    id: 'cp2',
    title: 'Zomato Feast Fest — Metro Domination',
    client: 'Zomato',
    service_id: 'svc_transit_delhi_metro',
    location_id: 'loc_1',
    start_date: '2026-08-15',
    end_date: '2026-10-15',
    budget: 420000,
    status: 'Live',
    artwork: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?q=80&w=800&auto=format&fit=crop',
    notes: 'Concourse + gate wraps'
  },
  {
    id: 'cp3',
    title: 'Galaxy Z Fold — Airport Arrival',
    client: 'Samsung India',
    service_id: 'svc_airport_delhi',
    location_id: 'loc_2',
    start_date: '2026-09-01',
    end_date: '2026-12-01',
    budget: 890000,
    status: 'Live',
    artwork: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?q=80&w=800&auto=format&fit=crop',
    notes: 'T3 arrival + baggage belt'
  },
  {
    id: 'cp4',
    title: 'HDFC Millennia — Railway Concourse',
    client: 'HDFC Bank',
    service_id: 'svc_transit_mumbai_local_train',
    location_id: 'loc_6',
    start_date: '2026-07-10',
    end_date: '2026-09-10',
    budget: 310000,
    status: 'Completed',
    artwork: 'https://images.unsplash.com/photo-1565019011521-b0575cbb57c8?q=80&w=800&auto=format&fit=crop',
    notes: 'FOB panels + concourse'
  },
  {
    id: 'cp5',
    title: 'Coke Summer — Cyber Hub LED',
    client: 'Coca-Cola',
    service_id: 'svc_led',
    location_id: 'loc_7',
    start_date: '2026-09-10',
    end_date: '2026-10-10',
    budget: 260000,
    status: 'Live',
    artwork: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?q=80&w=800&auto=format&fit=crop',
    notes: '120 plays/day, day-parted'
  },
  {
    id: 'cp6',
    title: 'Phoenix Fest — Atrium Launch',
    client: 'Zomato',
    service_id: 'svc_retail_mumbai_malls',
    location_id: 'loc_5',
    start_date: '2026-10-05',
    end_date: '2026-10-20',
    budget: 180000,
    status: 'Scheduled',
    artwork: 'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?q=80&w=800&auto=format&fit=crop',
    notes: 'Atrium + sampling kiosk'
  },
  {
    id: 'cp7',
    title: 'Bus Shelter — Fintech Pilot',
    client: 'HDFC Bank',
    service_id: 'svc_transit_bengaluru_bus_shelters',
    location_id: 'loc_4',
    start_date: '2026-09-20',
    end_date: '2026-11-20',
    budget: 145000,
    status: 'Scheduled',
    artwork: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?q=80&w=800&auto=format&fit=crop',
    notes: '12 mupis cluster'
  }
];

export const initialInquiries = [
  {
    id: 'iq1',
    name: 'Priya Sharma',
    phone: '+91 98111 22334',
    email: 'priya@d2cbrand.in',
    company: 'GlowKart D2C',
    service_id: 'svc_retail_mumbai_malls',
    location_id: 'loc_5',
    duration: '1 Month',
    budget: '₹2L – ₹5L',
    message: 'Festive launch in Mumbai malls, need atrium + facade for 3 weeks in Oct.',
    stage: 'New',
    date: '2026-09-10',
    followup: '2026-09-14'
  },
  {
    id: 'iq2',
    name: 'Rahul Verma',
    phone: '+91 99300 11223',
    email: 'rahul@realty.in',
    company: 'Verma Estates',
    service_id: 'svc_outdoor_delhi',
    location_id: 'loc_3',
    duration: '3 Months',
    budget: '₹5L – ₹15L',
    message: 'New township on NH-48, need unipole + gantry combo.',
    stage: 'Quoted',
    date: '2026-09-08',
    followup: '2026-09-13'
  },
  {
    id: 'iq3',
    name: 'Sneha Kulkarni',
    phone: '+91 98450 66778',
    email: 'sneha@edtech.in',
    company: 'LearnLeap',
    service_id: 'svc_transit_delhi_metro',
    location_id: 'loc_9',
    duration: '6 Months',
    budget: '₹15L+',
    message: 'Admissions season — Rajiv Chowk + Central Hub domination.',
    stage: 'Contacted',
    date: '2026-09-11',
    followup: '2026-09-15'
  },
  {
    id: 'iq4',
    name: 'Amit Patel',
    phone: '+91 98102 33445',
    email: 'amit@finserve.in',
    company: 'PaySwift',
    service_id: 'svc_led',
    location_id: 'loc_7',
    duration: '2 Weeks',
    budget: '₹50K – ₹2L',
    message: 'App launch, need Cyber Hub LED with QR creative.',
    stage: 'New',
    date: '2026-09-12',
    followup: '2026-09-14'
  },
  {
    id: 'iq5',
    name: 'Divya Menon',
    phone: '+91 97400 55667',
    email: 'divya@jewels.in',
    company: 'Malabar Jewels',
    service_id: 'svc_airport_delhi',
    location_id: 'loc_2',
    duration: '3 Months',
    budget: '₹5L – ₹15L',
    message: 'Diwali campaign at T3 arrivals.',
    stage: 'Converted',
    date: '2026-09-05',
    followup: '—'
  }
];

export const initialMedia = [
  {
    id: 'm1',
    title: 'Highway Unipole — Night Glow',
    tag: 'Highway Billboards',
    service_id: 'svc_outdoor_delhi',
    url: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'm2',
    title: 'Metro Concourse Wrap',
    tag: 'Metro Station Ads',
    service_id: 'svc_transit_delhi_metro',
    url: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'm3',
    title: 'T3 Arrival Banner',
    tag: 'Airport Banners',
    service_id: 'svc_airport_delhi',
    url: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'm4',
    title: 'Bus Shelter Mupi — Day',
    tag: 'Bus Shelter Posters',
    service_id: 'svc_transit_bengaluru_bus_shelters',
    url: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'm5',
    title: 'Mall Atrium Launch',
    tag: 'Mall Atrium Displays',
    service_id: 'svc_retail_mumbai_malls',
    url: 'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'm6',
    title: 'Railway Concourse Wall',
    tag: 'Railway Station Hoardings',
    service_id: 'svc_transit_mumbai_local_train',
    url: 'https://images.unsplash.com/photo-1565019011521-b0575cbb57c8?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'm7',
    title: 'Cyber Hub LED — Evening',
    tag: 'Digital LED',
    service_id: 'svc_led',
    url: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'm8',
    title: 'City Night Centre',
    tag: 'Street Pole Kiosks',
    service_id: 'svc_kiosk_mumbai',
    url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?q=80&w=800&auto=format&fit=crop'
  },
  {
    id: 'm9',
    title: 'Times-Style LED Burst',
    tag: 'Digital LED',
    service_id: 'svc_led',
    url: 'https://images.unsplash.com/photo-1444653614773-995cb1ef9efa?q=80&w=800&auto=format&fit=crop'
  }
];

export const initialClients = [
  { id: 'cl1', name: 'Nike India', contact: 'Rohan Mehta', phone: '+91 98200 11223', email: 'rohan@nike.in' },
  { id: 'cl2', name: 'Zomato', contact: 'Ananya Rao', phone: '+91 99301 44556', email: 'ananya@zomato.com' },
  { id: 'cl3', name: 'Samsung India', contact: 'Vikram Iyer', phone: '+91 98111 77889', email: 'vikram@samsung.in' },
  { id: 'cl4', name: 'HDFC Bank', contact: 'Kavya Nair', phone: '+91 98450 22334', email: 'kavya@hdfc.in' },
  { id: 'cl5', name: 'Coca-Cola', contact: 'Arjun Kapoor', phone: '+91 98100 99001', email: 'arjun@coke.in' }
];

export const initialListings = [
  {
    id: 'b3c8f8b8-2e06-4e58-9a3b-287df53b1001',
    category: 'Transit',
    subcategory: 'Transport',
    title: 'City Express Low-Floor AC Bus Branding',
    location: 'Delhi NCR',
    price: 45000,
    media_type: 'Bus',
    reach: 650000,
    description: 'High-frequency city commuter bus fleet exterior wrapping covering prime arterial routes.',
    image_url: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?q=80&w=800&auto=format&fit=crop',
    created_at: new Date().toISOString()
  },
  {
    id: 'b3c8f8b8-2e06-4e58-9a3b-287df53b1002',
    category: 'Transit',
    subcategory: 'Transport',
    title: 'Delhi Metro Blue Line Full Train Wrap',
    location: 'Delhi / NCR',
    price: 185000,
    media_type: 'Metro',
    reach: 1200000,
    description: 'Full exterior wrap across 6-coach train traversing Dwarka to Noida/Vaishali.',
    image_url: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?q=80&w=800&auto=format&fit=crop',
    created_at: new Date().toISOString()
  },
  {
    id: 'b3c8f8b8-2e06-4e58-9a3b-287df53b1003',
    category: 'Transit',
    subcategory: 'Transport',
    title: 'Suburban Express Electric Train Panel',
    location: 'Mumbai',
    price: 95000,
    media_type: 'Train',
    reach: 900000,
    description: 'Internal commuter panel advertising across western railway network.',
    image_url: 'https://images.unsplash.com/photo-1565019011521-b0575cbb57c8?q=80&w=800&auto=format&fit=crop',
    created_at: new Date().toISOString()
  },
  {
    id: 'b3c8f8b8-2e06-4e58-9a3b-287df53b1004',
    category: 'Transit',
    subcategory: 'Transport',
    title: 'Airport Feeder Bus Back-Panel Wrap',
    location: 'Bengaluru',
    price: 38000,
    media_type: 'Bus',
    reach: 420000,
    description: 'High-visibility back-panel on Kempegowda International Airport Vayu Vajra volvo buses.',
    image_url: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?q=80&w=800&auto=format&fit=crop',
    created_at: new Date().toISOString()
  },
  {
    id: 'b3c8f8b8-2e06-4e58-9a3b-287df53b1005',
    category: 'Transit',
    subcategory: 'Metro Networks',
    title: 'Metro Station Platform Screen Doors (PSD)',
    location: 'Bengaluru (Namma Metro)',
    price: 75000,
    media_type: 'Metro',
    reach: 550000,
    description: 'Illuminated platform screen door branding at high-traffic interchange stations.',
    image_url: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?q=80&w=800&auto=format&fit=crop',
    created_at: new Date().toISOString()
  },
  {
    id: 'b3c8f8b8-2e06-4e58-9a3b-287df53b1006',
    category: 'Transit',
    subcategory: 'Metro Networks',
    title: 'Metro Pillar Wraps on MG Road',
    location: 'Bengaluru',
    price: 60000,
    media_type: 'Metro',
    reach: 800000,
    description: 'Consecutive metro pillar vinyl wraps along prime commercial stretch.',
    image_url: 'https://images.unsplash.com/photo-1509099836639-18ba1795216d?q=80&w=800&auto=format&fit=crop',
    created_at: new Date().toISOString()
  },
  {
    id: 'b3c8f8b8-2e06-4e58-9a3b-287df53b1007',
    category: 'Transit',
    subcategory: 'Railway Terminals',
    title: 'New Delhi Railway Concourse Mega Billboard',
    location: 'New Delhi',
    price: 140000,
    media_type: 'Train',
    reach: 1500000,
    description: 'Massive illuminated display at platform entry concourse with 24/7 footfall.',
    image_url: 'https://images.unsplash.com/photo-1565019011521-b0575cbb57c8?q=80&w=800&auto=format&fit=crop',
    created_at: new Date().toISOString()
  },
  {
    id: 'b3c8f8b8-2e06-4e58-9a3b-287df53b1008',
    category: 'Outdoor',
    subcategory: 'Billboards & Unipoles',
    title: 'Cyber City Arterial Unipole (Backlit)',
    location: 'Gurugram',
    price: 125000,
    media_type: 'Billboard',
    reach: 980000,
    description: 'Front-facing highway unipole catching top corporate commuters.',
    image_url: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?q=80&w=800&auto=format&fit=crop',
    created_at: new Date().toISOString()
  },
  {
    id: 'b3c8f8b8-2e06-4e58-9a3b-287df53b1009',
    category: 'Outdoor',
    subcategory: 'Digital Hoardings',
    title: 'Bandra Flyover Curved DOOH Screen',
    location: 'Mumbai',
    price: 210000,
    media_type: 'Digital Screen',
    reach: 1400000,
    description: 'P6 LED high-definition screen at Western Express Highway intersection.',
    image_url: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?q=80&w=800&auto=format&fit=crop',
    created_at: new Date().toISOString()
  },
  {
    id: 'b3c8f8b8-2e06-4e58-9a3b-287df53b1010',
    category: 'Airport',
    subcategory: 'Terminal Displays',
    title: 'T3 Departure Lounge Digital Totem',
    location: 'Delhi Airport',
    price: 275000,
    media_type: 'Digital Totem',
    reach: 850000,
    description: 'Premium UHD digital totems targeting high-net-worth business travelers.',
    image_url: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?q=80&w=800&auto=format&fit=crop',
    created_at: new Date().toISOString()
  }
];

